server {
    server_name localhost;
    listen 3003;

    server_tokens off;
    add_header Access-Control-Allow-Origin *;

    root /usr/share/nginx/html/widget;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /status {
        access_log off;
        default_type text/plain;
        add_header Content-Type text/plain;
        return 200 "alive";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        try_files $uri =404;
    }
}
